USE ROLE ACCOUNTADMIN;

-- Creation of the database
CREATE WAREHOUSE IF NOT EXISTS FRAUD_DETECT_WH;
CREATE DATABASE IF NOT EXISTS FRAUD_DETECT_DB;
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECT_SM;

USE FRAUD_DETECT_DB.FRAUD_DETECT_SM;

-- Creation of tables to store data
CREATE OR REPLACE file format csvformat
    skip_header = 1
    type = CSV;
